# Generated by Django 4.0.2 on 2022-02-14 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='m5',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='appid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personal'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='m1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='m2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='m3',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='m4',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='appid',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email_id',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator]),
        ),
    ]
