# Generated by Django 4.0.2 on 2022-02-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mark_m5_alter_mark_appid_alter_mark_m1_alter_mark_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='total',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
